# Generated by Django 5.2.14 on 2026-06-07 13:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("hello_app", "0003_note_group_shoppinglist_group"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(verbose_name="Повідомлення")),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_messages",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_messages",
                        to="auth.group",
                        verbose_name="Група",
                    ),
                ),
            ],
            options={
                "verbose_name": "Повідомлення чату",
                "verbose_name_plural": "Повідомлення чату",
                "ordering": ["timestamp"],
                "indexes": [
                    models.Index(
                        fields=["group", "timestamp"], name="chat_group_ts_idx"
                    )
                ],
            },
        ),
    ]
